services:
  db:
    image: pgvector/pgvector:pg16 # 专门集成了 vector 扩展的镜像
    container_name: smartkb-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345zxcvb
      - POSTGRES_DB=smart_db # 这里填你项目需要的数据库名
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data